services:
  postgres:
    container_name: pg-list-manager
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=list-manager'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=123456789'
    ports:
      - '5432:5432'
