spring:
  application:
    name: list-manager

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/list-manager
    username: postgres
    password: 12345678

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
