spring:
  application:
    name: list-manager

  mvc:
    static-path-pattern: "/**"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/list-manager
    username: postgres
    password: 12345678

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  web:
    resources:
      static-locations: "classpath:/static/list-manager-cli/"

server:
  port: 8080
